version: '3'
services:
  mvn:
    build: DockerJava
    volumes:
      - type: volume
        source: mydata
        target: /usr/src/boxfuse/target/
  web:
    image: tomcat:9
    ports: 
      - "8080:8080"
    volumes: 
      - type: volume
        source: mydata
        target: /usr/local/tomcat/webapps
volumes:
  mydata: ./mydata